#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# =============================================================================
#  SUPER MARIO BROS-STYLE ENGINE  --  "SMB FAMICOM EDITION"
#  Team Flames / Samsoft / Flames Co. (c) 1999-2026
# -----------------------------------------------------------------------------
#  Single-file Python platformer. Targets Python 3.14, runs on 3.10+.
#  - 60 FPS fixed timestep (Famicom-style timing)
#  - All 32 stages: World 1-1 ... 8-4
#  - 256x240 native resolution, scaled up, crisp nearest-neighbour
#  - ALL graphics & audio generated procedurally in code (no external assets)
#  - All-Stars-inspired aesthetic: rounded shapes, shaded palette, soft sky
#
#  This is original homebrew. It does NOT use Nintendo asset rips or the
#  official level layouts; every sprite is drawn here and every stage is
#  generated by the seeded level generator below.
#
#  Run:  pip install pygame-ce      (recommended for Python 3.14)
#        python super_cat_bros.py
#
#  Controls:
#     Arrows / A,D ....... move        Z / Space .......... jump
#     X / Shift .......... run + fire   Down ............... crouch / enter
#     Enter .............. start / pause Esc ................ quit
# =============================================================================

import sys, math, random, struct, array

try:
    import pygame
except ImportError:
    print("This game needs pygame. Install with:  pip install pygame-ce")
    sys.exit(1)

# ----------------------------------------------------------------------------
#  CONFIG
# ----------------------------------------------------------------------------
TILE      = 16
NATIVE_W  = 256            # 16 tiles wide
NATIVE_H  = 240            # 15 tiles tall
SCALE     = 3
WIN_W     = NATIVE_W * SCALE
WIN_H     = NATIVE_H * SCALE
FPS       = 60
ROWS      = NATIVE_H // TILE          # 15
COLS_VIS  = NATIVE_W // TILE          # 16

GRAVITY   = 0.42          # enemies / items (kept simple)
MAX_FALL  = 7.0

# --- PLAYER PHYSICS: faithful SMB1 fixed-point model -------------------------
# Horizontal speeds/accels are the documented SMB1 values (hex / 4096 = px/frame
# at 60fps). Jump uses SMB1's scheme: a constant launch speed, with gravity
# *latched to a speed tier* at takeoff and lower while the button is held and
# rising -- so a full-run jump goes noticeably higher and farther than a
# standing one, exactly like the original.
P_MIN_WALK  = 0x0130 / 4096    # 0.0742  speed floor when a direction is tapped
P_MAX_WALK  = 0x1900 / 4096    # 1.5625  walk cap (run button up)
P_MAX_RUN   = 0x2900 / 4096    # 2.5625  run cap  (run button held)
P_WALK_ACC  = 0x0098 / 4096    # 0.0371
P_RUN_ACC   = 0x00E4 / 4096    # 0.0557
P_DECEL     = 0x00D0 / 4096    # 0.0508  release friction / ease toward walk cap
P_SKID_DEC  = 0x01A0 / 4096    # 0.1016  skid (turn-around) deceleration
P_JUMP_VY     = -0x4000 / 4096 # -4.0    constant initial upward speed
P_TIER_MID    = 0x1000 / 4096  # 1.0     |vx| >= this -> jump tier 1
P_TIER_FAST   = 0x2500 / 4096  # 2.3125  |vx| >= this -> jump tier 2
P_GRAV_HOLD   = (0x2800/65536, 0x2300/65536, 0x1E00/65536)  # rising + held: .156/.137/.117
P_GRAV_FALL   = (0x6000/65536, 0x6000/65536, 0x6800/65536)  # falling/released: .375/.375/.406
P_MAX_FALL    = 4.5
P_STOMP_BOUNCE = -3.6

# ----------------------------------------------------------------------------
#  PALETTE  (All-Stars-flavoured: brighter + shaded)
# ----------------------------------------------------------------------------
C = {
    "sky":      (104, 168, 252),
    "sky_dk":   (60, 110, 220),
    "black":    (12, 12, 20),
    "white":    (252, 252, 252),
    "cloud":    (236, 244, 255),
    "cloud_sh": (188, 212, 248),
    "hill":     (96, 196, 96),
    "hill_dk":  (56, 148, 64),
    "bush":     (72, 184, 88),
    "ground":   (198, 118, 58),
    "ground_dk":(150, 78, 36),
    "ground_lt":(228, 158, 96),
    "brick":    (200, 100, 60),
    "brick_dk": (150, 64, 36),
    "brick_lt": (236, 150, 110),
    "qblock":   (252, 200, 64),
    "qblock_dk":(208, 140, 16),
    "qblock_lt":(255, 236, 150),
    "used":     (160, 110, 60),
    "used_dk":  (110, 70, 36),
    "pipe":     (72, 200, 96),
    "pipe_dk":  (36, 140, 60),
    "pipe_lt":  (150, 240, 160),
    "flag":     (96, 220, 110),
    "pole":     (220, 220, 220),
    "pole_dk":  (150, 150, 160),
    # underground
    "u_bg":     (8, 8, 30),
    "u_brick":  (60, 120, 220),
    "u_brick_dk":(28, 70, 160),
    "u_brick_lt":(120, 180, 255),
    # castle
    "c_bg":     (24, 16, 28),
    "c_brick":  (180, 180, 188),
    "c_brick_dk":(110, 110, 120),
    "c_brick_lt":(220, 220, 228),
    "lava":     (236, 92, 36),
    "lava_lt":  (255, 168, 80),
    # mario
    "m_red":    (228, 56, 52),
    "m_red_dk": (168, 32, 36),
    "m_skin":   (252, 200, 156),
    "m_skin_dk":(208, 148, 104),
    "m_brown":  (120, 60, 24),
    "m_blue":   (60, 80, 200),
    "m_blue_dk":(36, 48, 150),
    "m_shoe":   (96, 52, 24),
    # fire mario
    "f_red":    (236, 64, 56),
    "f_white":  (250, 250, 250),
    "f_white_dk":(210, 210, 220),
    # enemies
    "goom":     (164, 96, 40),
    "goom_dk":  (108, 58, 22),
    "goom_lt":  (210, 150, 90),
    "koopa":    (76, 196, 84),
    "koopa_dk": (40, 140, 56),
    "koopa_sk": (252, 216, 120),
    "shell":    (84, 200, 96),
    "shell_dk": (36, 132, 56),
    "piranha":  (228, 64, 84),
    "piranha_dk":(168, 36, 56),
    "piranha_w":(252, 252, 252),
    # items
    "mush_red": (228, 56, 52),
    "mush_w":   (252, 248, 240),
    "mush_stem":(248, 224, 180),
    "flower_r": (236, 72, 64),
    "flower_y": (252, 216, 96),
    "flower_g": (72, 196, 96),
    "star":     (252, 232, 88),
    "star_dk":  (224, 168, 32),
    "coin":     (252, 216, 96),
    "coin_dk":  (208, 148, 24),
    "fire":     (252, 140, 48),
    "fire_lt":  (255, 224, 120),
}

# ----------------------------------------------------------------------------
#  PROCEDURAL SPRITE FACTORY
#  All sprites are drawn here into Surfaces and cached.  16x16 (small) or
#  16x32 (tall).  Rounded shapes + shading for the All-Stars feel.
# ----------------------------------------------------------------------------
def surf(w, h):
    s = pygame.Surface((w, h), pygame.SRCALPHA)
    return s

def rrect(s, color, rect, r=3):
    pygame.draw.rect(s, color, rect, border_radius=r)

SPR = {}   # sprite cache

def build_player_sprites():
    """Draw Mario-style plumber: small + big, idle/walk/jump/skid, normal+fire."""
    def draw_small(palette, frame):
        s = surf(16, 16)
        red, redd, sk, skd, ov, ovd, sh = palette
        # hat
        rrect(s, red, (3, 1, 10, 4), 2)
        rrect(s, redd, (3, 3, 10, 2), 1)
        pygame.draw.rect(s, red, (1, 3, 3, 2))      # brim
        # face
        rrect(s, sk, (4, 5, 8, 5), 2)
        pygame.draw.rect(s, skd, (4, 8, 8, 2))
        pygame.draw.rect(s, C["m_brown"], (10, 6, 2, 3))  # hair side
        pygame.draw.rect(s, C["black"], (9, 6, 1, 2))     # eye
        pygame.draw.rect(s, C["m_brown"], (5, 9, 5, 1))   # moustache
        # body / overalls
        rrect(s, ov, (3, 10, 10, 4), 2)
        pygame.draw.rect(s, red, (3, 10, 3, 3))           # arm
        pygame.draw.rect(s, red, (10, 10, 3, 3))
        # legs (frame anim)
        if frame == 0:
            pygame.draw.rect(s, ovd, (4, 13, 3, 2))
            pygame.draw.rect(s, ovd, (9, 13, 3, 2))
            pygame.draw.rect(s, sh, (3, 15, 4, 1))
            pygame.draw.rect(s, sh, (9, 15, 4, 1))
        else:
            pygame.draw.rect(s, ovd, (5, 13, 3, 2))
            pygame.draw.rect(s, ovd, (10, 13, 2, 2))
            pygame.draw.rect(s, sh, (3, 15, 4, 1))
            pygame.draw.rect(s, sh, (11, 14, 4, 1))
        return s

    def draw_big(palette, frame, crouch=False):
        s = surf(16, 32)
        red, redd, sk, skd, ov, ovd, sh = palette
        top = 10 if crouch else 0
        # hat
        rrect(s, red, (3, top+1, 11, 4), 2)
        rrect(s, redd, (3, top+3, 11, 2), 1)
        pygame.draw.rect(s, red, (1, top+3, 3, 2))
        # face
        rrect(s, sk, (4, top+5, 9, 6), 2)
        pygame.draw.rect(s, skd, (4, top+9, 9, 2))
        pygame.draw.rect(s, C["m_brown"], (11, top+7, 2, 3))
        pygame.draw.rect(s, C["black"], (9, top+7, 1, 2))
        pygame.draw.rect(s, C["m_brown"], (5, top+10, 6, 1))  # moustache
        if crouch:
            # crouched: compact body
            rrect(s, ov, (2, top+12, 12, 8), 3)
            pygame.draw.rect(s, red, (2, top+12, 3, 4))
            pygame.draw.rect(s, red, (11, top+12, 3, 4))
            pygame.draw.rect(s, sh, (2, 30, 5, 2))
            pygame.draw.rect(s, sh, (9, 30, 5, 2))
            return s
        # shirt + overalls
        rrect(s, red, (2, top+11, 12, 6), 3)        # shirt/arms
        rrect(s, ov, (4, top+15, 8, 9), 2)          # overalls front
        pygame.draw.rect(s, ovd, (4, top+15, 8, 2))
        pygame.draw.circle(s, C["qblock"], (6, top+18), 1)   # button
        pygame.draw.circle(s, C["qblock"], (10, top+18), 1)
        # hands
        pygame.draw.rect(s, sk, (1, top+15, 3, 3))
        pygame.draw.rect(s, sk, (12, top+15, 3, 3))
        # legs
        if frame == 0:
            rrect(s, ovd, (4, top+23, 4, 6), 1)
            rrect(s, ovd, (9, top+23, 4, 6), 1)
            pygame.draw.rect(s, sh, (3, 30, 5, 2))
            pygame.draw.rect(s, sh, (9, 30, 5, 2))
        elif frame == 1:
            rrect(s, ovd, (5, top+23, 4, 6), 1)
            rrect(s, ovd, (10, top+23, 3, 6), 1)
            pygame.draw.rect(s, sh, (3, 30, 5, 2))
            pygame.draw.rect(s, sh, (11, 29, 5, 2))
        else:
            rrect(s, ovd, (3, top+23, 4, 6), 1)
            rrect(s, ovd, (9, top+23, 4, 6), 1)
            pygame.draw.rect(s, sh, (2, 29, 5, 2))
            pygame.draw.rect(s, sh, (10, 30, 5, 2))
        return s

    normal = (C["m_red"], C["m_red_dk"], C["m_skin"], C["m_skin_dk"],
              C["m_blue"], C["m_blue_dk"], C["m_shoe"])
    fire   = (C["f_red"], C["m_red_dk"], C["m_skin"], C["m_skin_dk"],
              C["f_white"], C["f_white_dk"], C["m_shoe"])

    for tag, pal in (("", normal), ("f", fire)):
        SPR[f"p_small_idle{tag}"] = draw_small(pal, 0)
        SPR[f"p_small_walk0{tag}"] = draw_small(pal, 0)
        SPR[f"p_small_walk1{tag}"] = draw_small(pal, 1)
        SPR[f"p_small_jump{tag}"] = draw_small(pal, 1)
        SPR[f"p_small_skid{tag}"] = pygame.transform.flip(draw_small(pal, 1), True, False)
        SPR[f"p_big_idle{tag}"]  = draw_big(pal, 0)
        SPR[f"p_big_walk0{tag}"] = draw_big(pal, 0)
        SPR[f"p_big_walk1{tag}"] = draw_big(pal, 1)
        SPR[f"p_big_walk2{tag}"] = draw_big(pal, 2)
        SPR[f"p_big_jump{tag}"]  = draw_big(pal, 1)
        SPR[f"p_big_crouch{tag}"] = draw_big(pal, 0, crouch=True)


def build_enemy_sprites():
    # Goomba
    def goomba(frame):
        s = surf(16, 16)
        rrect(s, C["goom_dk"], (1, 3, 14, 9), 6)
        rrect(s, C["goom"], (1, 2, 14, 8), 6)
        rrect(s, C["goom_lt"], (3, 3, 10, 3), 4)
        # eyes
        pygame.draw.rect(s, C["white"], (4, 5, 3, 3))
        pygame.draw.rect(s, C["white"], (9, 5, 3, 3))
        pygame.draw.rect(s, C["black"], (5, 6, 2, 2))
        pygame.draw.rect(s, C["black"], (9, 6, 2, 2))
        # angry brows
        pygame.draw.line(s, C["goom_dk"], (4, 4), (7, 5), 1)
        pygame.draw.line(s, C["goom_dk"], (11, 4), (8, 5), 1)
        # feet
        if frame == 0:
            pygame.draw.rect(s, C["goom_dk"], (2, 12, 4, 3))
            pygame.draw.rect(s, C["goom_dk"], (10, 12, 4, 3))
        else:
            pygame.draw.rect(s, C["goom_dk"], (1, 12, 4, 3))
            pygame.draw.rect(s, C["goom_dk"], (11, 12, 4, 3))
        return s
    SPR["goomba0"] = goomba(0)
    SPR["goomba1"] = goomba(1)
    flat = surf(16, 16)
    rrect(flat, C["goom_dk"], (1, 11, 14, 4), 3)
    rrect(flat, C["goom"], (2, 11, 12, 2), 2)
    SPR["goomba_flat"] = flat

    # Koopa (turtle)
    def koopa(frame):
        s = surf(16, 16)
        # shell
        rrect(s, C["koopa_dk"], (2, 5, 12, 10), 5)
        rrect(s, C["koopa"], (2, 4, 12, 9), 5)
        rrect(s, C["koopa_sk"], (4, 6, 8, 4), 3)
        pygame.draw.line(s, C["koopa_dk"], (8, 5), (8, 12), 1)
        # head
        rrect(s, C["koopa_sk"], (10, 1, 5, 6), 3)
        pygame.draw.rect(s, C["black"], (13, 3, 1, 2))
        # feet
        if frame == 0:
            pygame.draw.rect(s, C["koopa_sk"], (3, 14, 3, 2))
            pygame.draw.rect(s, C["koopa_sk"], (9, 14, 3, 2))
        else:
            pygame.draw.rect(s, C["koopa_sk"], (4, 14, 3, 2))
            pygame.draw.rect(s, C["koopa_sk"], (10, 14, 3, 2))
        return s
    SPR["koopa0"] = koopa(0)
    SPR["koopa1"] = koopa(1)
    shell = surf(16, 16)
    rrect(shell, C["shell_dk"], (2, 5, 12, 9), 5)
    rrect(shell, C["shell"], (2, 4, 12, 8), 5)
    rrect(shell, C["koopa_sk"], (4, 6, 8, 3), 3)
    for i in range(3):
        pygame.draw.line(shell, C["shell_dk"], (4+i*3, 5), (4+i*3, 11), 1)
    SPR["shell"] = shell

    # Piranha plant
    def piranha(open_):
        s = surf(16, 16)
        # stem
        pygame.draw.rect(s, C["pipe_dk"], (6, 8, 4, 8))
        pygame.draw.rect(s, C["pipe"], (7, 8, 2, 8))
        # head
        rrect(s, C["piranha_dk"], (2, 1, 12, 8), 5)
        rrect(s, C["piranha"], (2, 1, 12, 7), 5)
        # spots
        pygame.draw.circle(s, C["piranha_w"], (5, 4), 1)
        pygame.draw.circle(s, C["piranha_w"], (11, 4), 1)
        # mouth
        if open_:
            pygame.draw.rect(s, C["white"], (4, 4, 8, 2))
        else:
            pygame.draw.rect(s, C["piranha_dk"], (4, 4, 8, 1))
        return s
    SPR["piranha0"] = piranha(False)
    SPR["piranha1"] = piranha(True)


def build_item_sprites():
    # Mushroom
    m = surf(16, 16)
    rrect(m, C["mush_red"], (1, 1, 14, 9), 6)
    pygame.draw.circle(m, C["mush_w"], (5, 4), 2)
    pygame.draw.circle(m, C["mush_w"], (11, 5), 2)
    pygame.draw.circle(m, C["mush_w"], (8, 3), 1)
    rrect(m, C["mush_stem"], (4, 8, 8, 7), 2)
    pygame.draw.rect(m, C["black"], (6, 10, 1, 2))
    pygame.draw.rect(m, C["black"], (10, 10, 1, 2))
    SPR["mushroom"] = m
    # 1up
    g = surf(16, 16)
    rrect(g, C["flower_g"], (1, 1, 14, 9), 6)
    pygame.draw.circle(g, C["mush_w"], (5, 4), 2)
    pygame.draw.circle(g, C["mush_w"], (11, 5), 2)
    rrect(g, C["mush_stem"], (4, 8, 8, 7), 2)
    pygame.draw.rect(g, C["black"], (6, 10, 1, 2))
    pygame.draw.rect(g, C["black"], (10, 10, 1, 2))
    SPR["oneup"] = g
    # Fire flower
    def flower(frame):
        s = surf(16, 16)
        pygame.draw.rect(s, C["flower_g"], (7, 9, 2, 6))
        pygame.draw.circle(s, C["flower_g"], (5, 11), 2)
        pygame.draw.circle(s, C["flower_g"], (11, 12), 2)
        cols = [C["flower_r"], C["flower_y"], C["flower_g"], C["m_blue"]]
        outer = cols[frame % 4]
        rrect(s, outer, (2, 1, 12, 8), 5)
        rrect(s, C["flower_y"], (5, 3, 6, 4), 3)
        pygame.draw.circle(s, C["white"], (8, 5), 1)
        return s
    for i in range(4):
        SPR[f"flower{i}"] = flower(i)
    # Star
    def star(frame):
        s = surf(16, 16)
        col = C["star"] if frame % 2 == 0 else C["star_dk"]
        pts = []
        cx, cy = 8, 8
        for i in range(10):
            ang = -math.pi/2 + i*math.pi/5
            r = 7 if i % 2 == 0 else 3
            pts.append((cx + math.cos(ang)*r, cy + math.sin(ang)*r))
        pygame.draw.polygon(s, col, pts)
        pygame.draw.polygon(s, C["star_dk"], pts, 1)
        pygame.draw.rect(s, C["black"], (5, 7, 1, 2))
        pygame.draw.rect(s, C["black"], (10, 7, 1, 2))
        return s
    for i in range(2):
        SPR[f"star{i}"] = star(i)
    # Coin (4 spin frames)
    def coin(w):
        s = surf(16, 16)
        if w <= 1:
            return s
        rrect(s, C["coin_dk"], (8 - w//2, 2, w, 12), 2)
        rrect(s, C["coin"], (8 - w//2 + 1, 3, max(1, w-2), 10), 2)
        if w >= 8:
            pygame.draw.rect(s, C["coin_dk"], (7, 5, 2, 6))
        return s
    for i, w in enumerate((10, 6, 2, 6)):
        SPR[f"coin{i}"] = coin(w)
    # Fireball
    def fb(frame):
        s = surf(8, 8)
        pygame.draw.circle(s, C["fire"], (4, 4), 4)
        pygame.draw.circle(s, C["fire_lt"], (4, 4), 2)
        return s
    SPR["fireball"] = fb(0)


# ----------------------------------------------------------------------------
#  PROCEDURAL TILE SURFACES (per-theme)
# ----------------------------------------------------------------------------
TILE_CACHE = {}

def make_tile(kind, theme):
    key = (kind, theme)
    if key in TILE_CACHE:
        return TILE_CACHE[key]
    s = surf(TILE, TILE)

    if kind == "ground":
        base, dk, lt = C["ground"], C["ground_dk"], C["ground_lt"]
        if theme == "under":
            base, dk, lt = C["u_brick"], C["u_brick_dk"], C["u_brick_lt"]
        elif theme == "castle":
            base, dk, lt = C["c_brick"], C["c_brick_dk"], C["c_brick_lt"]
        s.fill(base)
        pygame.draw.rect(s, lt, (0, 0, TILE, 2))
        pygame.draw.rect(s, dk, (0, TILE-3, TILE, 3))
        # brick pattern
        for yy in range(0, TILE, 8):
            off = 0 if (yy // 8) % 2 == 0 else 8
            for xx in range(-8, TILE, 16):
                pygame.draw.rect(s, dk, (xx+off, yy, 1, 8))
            pygame.draw.line(s, dk, (0, yy+7), (TILE, yy+7))

    elif kind == "brick":
        base, dk, lt = C["brick"], C["brick_dk"], C["brick_lt"]
        if theme == "under":
            base, dk, lt = C["u_brick"], C["u_brick_dk"], C["u_brick_lt"]
        elif theme == "castle":
            base, dk, lt = C["c_brick"], C["c_brick_dk"], C["c_brick_lt"]
        s.fill(base)
        pygame.draw.rect(s, lt, (0, 0, TILE, 2))
        for yy in range(0, TILE, 8):
            off = 0 if (yy // 8) % 2 == 0 else 8
            pygame.draw.line(s, dk, (0, yy), (TILE, yy))
            pygame.draw.line(s, dk, (off, yy), (off, yy+8))
            pygame.draw.line(s, dk, ((off+8) % 16, yy), ((off+8) % 16, yy+8))

    elif kind in ("qblock", "used"):
        if kind == "qblock":
            base, dk, lt = C["qblock"], C["qblock_dk"], C["qblock_lt"]
        else:
            base, dk, lt = C["used"], C["used_dk"], C["used"]
        rrect(s, dk, (0, 0, TILE, TILE), 2)
        rrect(s, base, (1, 1, TILE-2, TILE-2), 2)
        pygame.draw.rect(s, lt, (2, 2, TILE-4, 2))
        # rivets
        for cx, cy in ((2, 2), (13, 2), (2, 13), (13, 13)):
            pygame.draw.rect(s, dk, (cx, cy, 1, 1))
        if kind == "qblock":
            f = pygame.font.SysFont(None, 0)
            pygame.draw.rect(s, dk, (6, 4, 4, 1))
            pygame.draw.rect(s, dk, (9, 4, 1, 3))
            pygame.draw.rect(s, dk, (7, 7, 2, 1))
            pygame.draw.rect(s, dk, (7, 9, 2, 2))
        TILE_CACHE[key] = s
        return s

    elif kind == "stair":
        s.fill(C["ground"] if theme != "castle" else C["c_brick"])
        pygame.draw.rect(s, C["ground_lt"] if theme != "castle" else C["c_brick_lt"], (0, 0, TILE, 2))
        pygame.draw.rect(s, C["ground_dk"] if theme != "castle" else C["c_brick_dk"], (0, TILE-2, TILE, 2))

    elif kind == "platform":
        s.fill((0, 0, 0, 0))
        rrect(s, C["ground_dk"], (0, 0, TILE, 6), 2)
        rrect(s, C["ground"], (0, 0, TILE, 4), 2)
        pygame.draw.rect(s, C["ground_lt"], (0, 0, TILE, 1))

    elif kind == "lava":
        s.fill(C["lava"])
        pygame.draw.rect(s, C["lava_lt"], (0, 0, TILE, 3))
        for xx in range(0, TILE, 4):
            pygame.draw.rect(s, C["lava_lt"], (xx, 0, 2, 1))

    TILE_CACHE[key] = s
    return s


# ----------------------------------------------------------------------------
#  PROCEDURAL AUDIO ENGINE  --  the "math OST engine"
#  Everything (SFX + the full soundtrack) is synthesized from math:
#  square + triangle + noise oscillators rendered to 16-bit PCM buffers.
#  No .mp3 / .wav / external files are loaded -- ever.
#
#  The melodies are ORIGINAL chiptune compositions written for this engine,
#  in the bright NES/Mario *style* (Koji-Kondo-flavoured, copyright-free):
#  bouncy overworld, sparse minor underground, airy athletic, dark castle,
#  a triumphant title fanfare, a star-power rush, and a course-clear jingle.
#  Each stage theme is transposed per world so all 32 levels feel distinct.
# ----------------------------------------------------------------------------
RATE = 22050                       # mixer/render sample rate (chiptune-friendly)
_NIDX = {'C':0, 'C#':1, 'D':2, 'D#':3, 'E':4, 'F':5,
         'F#':6, 'G':7, 'G#':8, 'A':9, 'A#':10, 'B':11}

def NN(s):                         # note name -> MIDI number, e.g. "C4" -> 60
    return 12 * (int(s[-1]) + 1) + _NIDX[s[:-1]]

def _freq(m):                      # MIDI -> Hz (equal temperament)
    return 440.0 * 2 ** ((m - 69) / 12.0)


# ---- ORIGINAL COMPOSITIONS (note, duration-in-16ths) ------------------------
# Drum tokens: 'k' kick, 's' snare, 'h' hat, None rest.
_DRUM_ROCK = [('k',2),('h',2),('s',2),('h',2),('k',2),('h',2),('s',2),('h',2)] * 4
_DRUM_OFF  = [(None,2),('h',2)] * 8 * 1 + [(None,2),('h',2)] * 8
_DRUM_OFF  = [(None,2),('h',2)] * 16
_DRUM_DOOM = [('k',4),(None,4),('k',4),(None,4)] * 4

TRACKS = {
    "over": {
        "bpm": 150, "duty": 0.5,
        "mel": [
            ("G4",2),("C5",2),("E5",2),("G5",2),("E5",2),("C5",2),("D5",4),
            ("F5",2),("E5",2),("D5",2),("C5",2),("E5",2),("G5",2),("C5",4),
            ("A4",2),("C5",2),("E5",2),("A5",2),("G5",2),("E5",2),("D5",4),
            ("C5",2),("E5",2),("G5",2),("C6",2),("B5",2),("G5",2),("C5",4),
        ],
        "bass": [
            ("C3",4),("G3",4),("C3",4),("G3",4),
            ("F2",4),("C3",4),("F2",4),("G2",4),
            ("A2",4),("E3",4),("A2",4),("G2",4),
            ("C3",4),("G2",4),("C3",4),("G2",4),
        ],
        "drum": _DRUM_ROCK,
    },
    "under": {
        "bpm": 132, "duty": 0.25,
        "mel": [
            ("A4",1),(None,1),("A4",1),(None,1),("C5",1),(None,1),("A4",1),(None,1),("G4",2),(None,2),("E4",2),(None,2),
            ("F4",1),(None,1),("F4",1),(None,1),("A4",1),(None,1),("F4",1),(None,1),("E4",2),(None,2),("C4",2),(None,2),
            ("G4",1),(None,1),("G4",1),(None,1),("B4",1),(None,1),("G4",1),(None,1),("F4",2),(None,2),("D4",2),(None,2),
            ("A4",2),(None,2),("E4",2),(None,2),("A4",2),(None,2),(None,4),
        ],
        "bass": [
            ("A2",8),("E2",8),("F2",8),("E2",8),
            ("G2",8),("D2",8),("A2",8),("A2",8),
        ],
        "drum": _DRUM_OFF,
    },
    "sky": {
        "bpm": 168, "duty": 0.5,
        "mel": [
            ("D5",2),("F#5",2),("A5",2),("D6",2),("A5",2),("F#5",2),("A5",4),
            ("E5",2),("G5",2),("B5",2),("E6",2),("B5",2),("G5",2),("B5",4),
            ("F#5",2),("A5",2),("D6",2),("F#6",2),("D6",2),("A5",2),("D6",4),
            ("A5",2),("D6",2),("F#6",2),("A6",2),("G6",2),("E6",2),("D6",4),
        ],
        "bass": [
            ("D3",4),("A2",4),("D3",4),("A2",4),
            ("E3",4),("B2",4),("E3",4),("B2",4),
            ("F#3",4),("C#3",4),("F#3",4),("C#3",4),
            ("D3",4),("A2",4),("D3",4),("A2",4),
        ],
        "drum": _DRUM_ROCK,
    },
    "castle": {
        "bpm": 120, "duty": 0.5,
        "mel": [
            ("D4",2),("D#4",2),("D4",2),("C#4",2),("D4",4),("A3",4),
            ("A#3",2),("A3",2),("G#3",2),("A3",2),("D4",4),("C#4",4),
            ("D4",2),("F4",2),("D4",2),("A#3",2),("A3",4),("G#3",4),
            ("A3",2),("A#3",2),("A3",2),("G#3",2),("A3",4),("D4",4),
        ],
        "bass": [
            ("D2",8),("A2",8),("D2",8),("A2",8),
            ("D#2",8),("A2",8),("A2",8),("D2",8),
        ],
        "drum": _DRUM_DOOM,
    },
    "title": {
        "bpm": 140, "duty": 0.5,
        "mel": [
            ("C5",2),("E5",2),("G5",2),("C6",4),("G5",2),("E5",2),("C5",2),
            ("D5",2),("F5",2),("A5",2),("D6",4),("A5",2),("F5",2),("D5",2),
            ("E5",2),("G5",2),("C6",2),("E6",4),("C6",2),("G5",2),("E5",2),
            ("G5",4),("F5",2),("E5",2),("D5",2),("C5",6),
        ],
        "bass": [
            ("C3",4),("E3",4),("G3",4),("C3",4),
            ("D3",4),("F3",4),("A3",4),("D3",4),
            ("E3",4),("G3",4),("C4",4),("G3",4),
            ("G3",4),("G2",4),("C3",4),("C3",4),
        ],
        "drum": _DRUM_ROCK,
    },
    "star": {
        "bpm": 192, "duty": 0.25,
        "mel": [
            ("C5",2),("E5",2),("G5",2),("C6",2),("E5",2),("G5",2),("C6",2),("E6",2),
            ("D5",2),("F5",2),("A5",2),("D6",2),("F5",2),("A5",2),("D6",2),("F6",2),
        ],
        "bass": [
            ("C3",2),("C3",2),("C3",2),("C3",2),("C3",2),("C3",2),("C3",2),("C3",2),
            ("D3",2),("D3",2),("D3",2),("D3",2),("D3",2),("D3",2),("D3",2),("D3",2),
        ],
        "drum": _DRUM_ROCK[:16] * 2,
    },
}


class Audio:
    WORLD_SEMI = [0, 2, -2, 3, 5, -4, 7, 1]      # per-world transposition

    def __init__(self):
        self.ok = False
        self.snd = {}
        self.music_cache = {}
        self.cur = None
        self.mch = None
        try:
            pygame.mixer.pre_init(RATE, -16, 1, 512)
            pygame.mixer.init()
            pygame.mixer.set_num_channels(16)
            self.mch = pygame.mixer.Channel(0)   # reserved for music
            self.ok = True
        except Exception:
            self.ok = False
            return
        self._build_sfx()

    # ---- SFX (short square blips) -------------------------------------------
    def _build_sfx(self):
        self._sfx("jump",  [(523, 30), (784, 60)])
        self._sfx("stomp", [(220, 40), (110, 50)])
        self._sfx("coin",  [(988, 40), (1319, 80)])
        self._sfx("bump",  [(196, 50)])
        self._sfx("power", [(523, 40), (659, 40), (784, 60), (1047, 80)])
        self._sfx("fire",  [(880, 25), (440, 35)])
        self._sfx("kick",  [(330, 30), (165, 40)])
        self._sfx("die",   [(440, 90), (330, 90), (262, 160)])
        self._sfx("1up",   [(659, 40), (784, 40), (988, 40), (1319, 90)])
        self._sfx("flag",  [(523, 40), (659, 40), (784, 40), (1047, 90)])
        self._sfx("brick", [(294, 40), (147, 50)])

    def _blip(self, freq, ms, vol=0.16):
        n = int(RATE * ms / 1000)
        buf = array.array("h")
        period = max(1, int(RATE / max(1, freq)))
        amp = int(32767 * vol)
        for i in range(n):
            fade = 1.0 if i < n - 300 else max(0.0, (n - i) / 300.0)
            v = amp if (i % period) < period // 2 else -amp
            buf.append(int(v * fade))
        return buf

    def _sfx(self, name, notes):
        if not self.ok:
            return
        full = array.array("h")
        for f, ms in notes:
            full.extend(self._blip(f, ms))
        try:
            self.snd[name] = pygame.mixer.Sound(buffer=full.tobytes())
        except Exception:
            self.ok = False

    def play(self, name):
        if self.ok and name in self.snd:
            try:
                self.snd[name].play()
            except Exception:
                pass

    # ---- MUSIC SYNTH --------------------------------------------------------
    def _note(self, note, n, wave, vol, duty, semi):
        if n <= 0:
            return []
        if note is None:
            return [0] * n
        inc = _freq(NN(note) + semi) / RATE
        amp = int(32767 * vol)
        if wave == "square":
            body = [amp if (i * inc) % 1.0 < duty else -amp for i in range(n)]
        elif wave == "tri":
            body = [int(amp * (4 * abs(((i * inc) % 1.0) - 0.5) - 1)) for i in range(n)]
        else:
            body = [0] * n
        a = max(1, int(n * 0.04))                # attack/release to kill clicks
        r = max(1, int(n * 0.12))
        for i in range(min(a, n)):
            body[i] = int(body[i] * i / a)
        for i in range(min(r, n)):
            body[n - 1 - i] = int(body[n - 1 - i] * i / r)
        return body

    def _seq(self, events, bpm, wave, vol, duty, semi):
        sec16 = 60.0 / bpm / 4.0
        out = []
        for note, d in events:
            out.extend(self._note(note, int(RATE * sec16 * d), wave, vol, duty, semi))
        return out

    def _hit(self, kind, n):
        if n <= 0:
            return []
        if kind is None:
            return [0] * n
        if kind == "h":
            L = min(n, int(RATE * 0.02)); amp = 3200
            seg = [random.randint(-amp, amp) for _ in range(L)]
        elif kind == "s":
            L = min(n, int(RATE * 0.06)); amp = 6500
            seg = [random.randint(-amp, amp) for _ in range(L)]
        else:  # kick: short descending sine thump
            L = min(n, int(RATE * 0.07)); amp = 8000
            seg = [int(amp * math.sin(2 * math.pi * (95 * (1 - i / L)) * i / RATE)) for i in range(L)]
        for i in range(L):
            seg[i] = int(seg[i] * (1 - i / L))
        return seg + [0] * (n - L)

    def _drum(self, events, bpm):
        sec16 = 60.0 / bpm / 4.0
        out = []
        for kind, d in events:
            out.extend(self._hit(kind, int(RATE * sec16 * d)))
        return out

    def _mix(self, chans):
        L = min(len(c) for c in chans)
        acc = [0] * L
        for c in chans:
            for i in range(L):
                acc[i] += c[i]
        out = array.array("h")
        for v in acc:
            out.append(32767 if v > 32767 else (-32768 if v < -32768 else v))
        return out

    def _build_track(self, theme, world):
        spec = TRACKS[theme]
        semi = 0 if theme in ("title", "star") else self.WORLD_SEMI[(world - 1) % 8]
        bpm = spec["bpm"]
        chans = [
            self._seq(spec["mel"], bpm, "square", 0.22, spec["duty"], semi),
            self._seq(spec["bass"], bpm, "tri", 0.24, 0.5, semi),
            self._drum(spec["drum"], bpm),
        ]
        return pygame.mixer.Sound(buffer=self._mix(chans).tobytes())

    def _build_jingle(self, name):
        if name == "clear":
            mel = [("C5",2),("D5",2),("E5",2),("F5",2),("G5",2),("A5",2),("B5",2),
                   ("C6",2),("E6",2),("G6",2),("C6",4),("E6",4)]
            bass = [("C3",8),("G3",8),("C3",8),("G3",4),("C3",4)]
            chans = [self._seq(mel, 156, "square", 0.24, 0.5, 0),
                     self._seq(bass, 156, "tri", 0.24, 0.5, 0)]
            return pygame.mixer.Sound(buffer=self._mix(chans).tobytes())
        return None

    def play_music(self, theme, world):
        if not self.ok:
            return
        key = (theme, world)
        if self.cur == key and self.mch.get_busy():
            return
        snd = self.music_cache.get(key)
        if snd is None:
            try:
                snd = self._build_track(theme, world)
            except Exception:
                snd = None
            self.music_cache[key] = snd
        self.cur = key
        if snd:
            try:
                self.mch.play(snd, loops=-1)
            except Exception:
                pass

    def stop_music(self):
        self.cur = None
        if self.mch:
            try:
                self.mch.stop()
            except Exception:
                pass

    def play_jingle(self, name):
        if not self.ok:
            return
        self.stop_music()
        key = ("jingle", name)
        s = self.music_cache.get(key)
        if s is None:
            try:
                s = self._build_jingle(name)
            except Exception:
                s = None
            self.music_cache[key] = s
        if s:
            try:
                s.play()
            except Exception:
                pass


# ----------------------------------------------------------------------------
#  LEVEL
#  Grid of single-char tile codes.  Generated procedurally + seeded.
#    '#' solid ground   'B' breakable brick   '?' question(item)
#    'Q' used block     'S' stair block       'L' lava
#    '|' flagpole       'X' axe/goal (castle)
#  Pipes & special entities are stored separately.
# ----------------------------------------------------------------------------
SOLID = set("#BQ?SX")

THEMES = {1: "over", 2: "under", 3: "sky", 0: "castle"}  # by (level index %4)

class Level:
    def __init__(self, world, stage):
        self.world = world
        self.stage = stage
        sub = stage % 4
        self.theme = THEMES[sub]
        self.is_castle = (sub == 0)
        self.is_under = (sub == 2)
        self.width = 180 + world * 12 + (stage % 4) * 8
        if self.is_castle:
            self.width = 150 + world * 6
        self.grid = [["-"] * self.width for _ in range(ROWS)]
        self.qcontents = {}      # (col,row) -> item string
        self.pipes = []          # (col, top_row, height, piranha_bool)
        self.enemies = []        # (col, row, kind)
        self.flag_col = self.width - 8
        self.bg = self._bg_color()
        self.start_col = 2
        self._generate()

    def _bg_color(self):
        if self.theme == "under":
            return C["u_bg"]
        if self.theme == "castle":
            return C["c_bg"]
        if self.theme == "sky":
            return C["sky_dk"]
        return C["sky"]

    def set(self, col, row, ch):
        if 0 <= col < self.width and 0 <= row < ROWS:
            self.grid[row][col] = ch

    def get(self, col, row):
        if 0 <= col < self.width and 0 <= row < ROWS:
            return self.grid[row][col]
        return "#" if row >= ROWS else "-"

    def solid(self, col, row):
        return self.get(col, row) in SOLID

    def _generate(self):
        rng = random.Random(self.world * 100 + self.stage)
        floor = ROWS - 2       # top of the 2-row ground
        # base ground
        for col in range(self.width):
            self.set(col, ROWS - 1, "#")
            self.set(col, ROWS - 2, "#")

        if self.is_castle:
            self._gen_castle(rng, floor)
            return

        col = 6
        last_pit = 0
        while col < self.flag_col - 6:
            roll = rng.random()
            # gaps / pits (more later in game)
            pit_chance = 0.06 + self.world * 0.012 + (0.05 if self.theme == "sky" else 0)
            if roll < pit_chance and col - last_pit > 6 and col > 16:
                gap = rng.randint(2, 3 if self.world < 4 else 4)
                for g in range(gap):
                    self.set(col + g, ROWS - 1, "-")
                    self.set(col + g, ROWS - 2, "-")
                col += gap + rng.randint(2, 4)
                last_pit = col
                continue

            if roll < 0.18:
                # question / brick row
                h = floor - rng.randint(3, 4)
                length = rng.randint(1, 4)
                for i in range(length):
                    c = col + i
                    if i == length // 2 and rng.random() < 0.55:
                        self.set(c, h, "?")
                        r = rng.random()
                        if r < 0.65:
                            self.qcontents[(c, h)] = "coin"
                        elif r < 0.86:
                            self.qcontents[(c, h)] = "mush"
                        elif r < 0.96:
                            self.qcontents[(c, h)] = "flower"
                        else:
                            self.qcontents[(c, h)] = "star"
                    else:
                        self.set(c, h, "B")
                if rng.random() < 0.4:
                    self.enemies.append((col + length + 2, floor - 1, "goomba"))
                col += length + rng.randint(2, 4)

            elif roll < 0.30:
                # pipe (maybe with piranha)
                ph = 1  # Mario's small height in tiles (14px → 1 tile)
                pir = rng.random() < 0.5
                self.pipes.append((col, ROWS - 2 - ph, ph, pir))
                col += rng.randint(4, 7)

            elif roll < 0.42:
                # floating platform of bricks
                h = floor - rng.randint(4, 6)
                length = rng.randint(3, 6)
                for i in range(length):
                    self.set(col + i, h, "B")
                if rng.random() < 0.5:
                    self.enemies.append((col + 1, h - 1, "koopa"))
                col += length + rng.randint(3, 5)

            elif roll < 0.55:
                # enemies on the ground
                n = rng.randint(1, 2 + self.world // 3)
                for i in range(n):
                    kind = "koopa" if rng.random() < 0.35 else "goomba"
                    self.enemies.append((col + i * 2, floor - 1, kind))
                col += n * 2 + rng.randint(3, 6)
            else:
                col += rng.randint(2, 5)

        # ending staircase + flagpole
        sc = self.flag_col - 10
        for i in range(7):
            for j in range(i + 1):
                self.set(sc + i, floor - j, "S")
        # flagpole
        fc = self.flag_col
        for r in range(2, floor):
            self.set(fc, r, "|")
        self.set(fc, 1, "|")

    def _gen_castle(self, rng, floor):
        col = 6
        while col < self.width - 14:
            roll = rng.random()
            if roll < 0.22 and col > 12:
                # lava pit
                gap = rng.randint(2, 3)
                for g in range(gap):
                    self.set(col + g, ROWS - 1, "L")
                    self.set(col + g, ROWS - 2, "L")
                col += gap + rng.randint(3, 5)
            elif roll < 0.45:
                h = floor - rng.randint(3, 5)
                for i in range(rng.randint(2, 4)):
                    self.set(col + i, h, "B")
                col += rng.randint(4, 7)
            elif roll < 0.62:
                self.enemies.append((col, floor - 1, "koopa"))
                col += rng.randint(4, 6)
            else:
                col += rng.randint(3, 6)
        # goal axe / bridge at the end
        gx = self.width - 10
        for r in range(floor - 1, ROWS):
            for c in range(gx - 2, gx + 4):
                if r == floor - 1:
                    self.set(c, r, "#")
        self.flag_col = gx
        for r in range(2, floor):
            self.set(gx, r, "|")
        self.set(gx, 1, "X")
        # boss
        self.enemies.append((gx - 6, floor - 1, "boss"))


# ----------------------------------------------------------------------------
#  ENTITIES
# ----------------------------------------------------------------------------
class Entity:
    def __init__(self, x, y, w, h):
        self.x = float(x); self.y = float(y)
        self.w = w; self.h = h
        self.vx = 0.0; self.vy = 0.0
        self.alive = True
        self.on_ground = False
    @property
    def rect(self):
        return pygame.Rect(int(self.x), int(self.y), self.w, self.h)
    def cx(self): return self.x + self.w / 2

def tile_collide_x(ent, level):
    ent.x += ent.vx
    r = ent.rect
    c0 = int(r.left // TILE); c1 = int(r.right // TILE)
    rr0 = int(r.top // TILE); rr1 = int(r.bottom // TILE)
    hit = False
    for cc in range(c0, c1 + 1):
        for rrw in range(rr0, rr1 + 1):
            if level.solid(cc, rrw):
                tr = pygame.Rect(cc*TILE, rrw*TILE, TILE, TILE)
                if r.colliderect(tr):
                    if ent.vx > 0:
                        ent.x = tr.left - ent.w
                    elif ent.vx < 0:
                        ent.x = tr.right
                    ent.vx = 0; hit = True
                    r = ent.rect
    return hit

def tile_collide_y(ent, level):
    ent.y += ent.vy
    r = ent.rect
    c0 = int(r.left // TILE); c1 = int(r.right // TILE)
    rr0 = int(r.top // TILE); rr1 = int(r.bottom // TILE)
    ent.on_ground = False
    head_tile = None
    for cc in range(c0, c1 + 1):
        for rrw in range(rr0, rr1 + 1):
            if level.solid(cc, rrw):
                tr = pygame.Rect(cc*TILE, rrw*TILE, TILE, TILE)
                if r.colliderect(tr):
                    if ent.vy > 0:
                        ent.y = tr.top - ent.h
                        ent.on_ground = True
                    elif ent.vy < 0:
                        ent.y = tr.bottom
                        head_tile = (cc, rrw)
                    ent.vy = 0
                    r = ent.rect
    return head_tile

def pipe_collide(ent, level):
    r = ent.rect
    for (pc, ptop, ph, _) in level.pipes:
        pr = pygame.Rect(pc*TILE, ptop*TILE, 2*TILE, ph*TILE)
        if r.colliderect(pr):
            # resolve simply: push out on smallest axis
            dx = min(r.right - pr.left, pr.right - r.left)
            dy = min(r.bottom - pr.top, pr.bottom - r.top)
            if dx < dy:
                if ent.cx() < pr.centerx:
                    ent.x = pr.left - ent.w
                else:
                    ent.x = pr.right
                ent.vx = 0
            else:
                if ent.y < pr.top:
                    ent.y = pr.top - ent.h
                    ent.on_ground = True
                    ent.vy = 0
                else:
                    ent.y = pr.bottom
                    ent.vy = 0
            r = ent.rect


class Player(Entity):
    def __init__(self, x, y):
        super().__init__(x, y, 12, 14)
        self.power = 0          # 0 small, 1 big, 2 fire
        self.facing = 1
        self.anim = 0.0
        self.invuln = 0
        self.star = 0
        self.crouch = False
        self.dead = False
        self.win = 0            # >0 = level-complete sequence timer
        self.fire_cd = 0
        self.prev_jump = False  # SMB jump state
        self.holding_jump = False
        self.jump_tier = 0

    def set_power(self, p):
        was = self.power
        self.power = p
        if p >= 1 and was == 0:
            self.h = 28
            self.y -= 14
        elif p == 0 and was >= 1:
            self.h = 14
            self.y += 14

    def hurt(self, game):
        if self.invuln > 0 or self.star > 0 or self.win:
            return
        if self.power >= 1:
            self.set_power(0)
            self.invuln = 90
            game.audio.play("power")
        else:
            self.die(game)

    def die(self, game):
        if self.dead:
            return
        self.dead = True
        self.vy = -8
        self.vx = 0
        game.audio.stop_music()
        game.audio.play("die")

    def update(self, game, keys):
        if self.dead:
            self.vy += GRAVITY
            self.y += self.vy
            return
        if self.win:
            return
        lvl = game.level
        left = keys[pygame.K_LEFT] or keys[pygame.K_a]
        right = keys[pygame.K_RIGHT] or keys[pygame.K_d]
        run = keys[pygame.K_x] or keys[pygame.K_LSHIFT] or keys[pygame.K_RSHIFT]
        down = keys[pygame.K_DOWN] or keys[pygame.K_s]
        self.crouch = down and self.power >= 1 and self.on_ground

        # ---- SMB1 horizontal movement (subpixel-accurate) ----
        if self.crouch:
            left = right = False
        move = -1 if (left and not right) else (1 if (right and not left) else 0)

        if move != 0:
            self.facing = move
            if self.vx * move < 0:                  # pressing against motion -> skid
                self.vx += P_SKID_DEC * move
                if abs(self.vx) < P_MIN_WALK:
                    self.vx = P_MIN_WALK * move      # finished turning around
            else:
                if abs(self.vx) < P_MIN_WALK:
                    self.vx = P_MIN_WALK * move
                self.vx += (P_RUN_ACC if run else P_WALK_ACC) * move
                cap = P_MAX_RUN if run else P_MAX_WALK
                if not run and abs(self.vx) > P_MAX_WALK:
                    self.vx -= P_DECEL * move         # released run: ease to walk cap
                elif abs(self.vx) > cap:
                    self.vx = cap * move
        else:
            if self.vx > 0:   self.vx = max(0.0, self.vx - P_DECEL)
            elif self.vx < 0: self.vx = min(0.0, self.vx + P_DECEL)
        self.vx = max(-P_MAX_RUN, min(P_MAX_RUN, self.vx))

        # ---- SMB1 jump: constant launch, speed-tiered & button-held gravity ----
        jb = keys[pygame.K_z] or keys[pygame.K_SPACE] or keys[pygame.K_UP]
        if jb and not self.prev_jump and self.on_ground:
            self.vy = P_JUMP_VY
            self.on_ground = False
            self.holding_jump = True
            sp = abs(self.vx)
            self.jump_tier = 2 if sp >= P_TIER_FAST else (1 if sp >= P_TIER_MID else 0)
            game.audio.play("jump")
        if not jb:
            self.holding_jump = False
        self.prev_jump = jb
        if self.vy < 0 and self.holding_jump:
            self.vy += P_GRAV_HOLD[self.jump_tier]    # floaty rise while held
        else:
            self.vy += P_GRAV_FALL[self.jump_tier]    # snappier fall / released
        self.vy = min(self.vy, P_MAX_FALL)

        # fire
        if self.fire_cd > 0: self.fire_cd -= 1
        if run and self.power == 2 and self.fire_cd == 0 and len([f for f in game.fireballs if f.alive]) < 2:
            fx = self.x + (self.w if self.facing > 0 else -4)
            game.fireballs.append(Fireball(fx, self.y + 6, self.facing))
            self.fire_cd = 18
            game.audio.play("fire")

        # collisions
        tile_collide_x(self, lvl)
        head = tile_collide_y(self, lvl)
        pipe_collide(self, lvl)
        if head:
            self._hit_block(game, head[0], head[1])

        # bounds
        if self.x < game.cam_x:
            self.x = game.cam_x; self.vx = 0
        if self.x < 0:
            self.x = 0

        # fall in pit / lava
        if self.y > NATIVE_H + 20:
            self.die(game)
        rr = int((self.y + self.h - 1) // TILE)
        cc = int(self.cx() // TILE)
        if lvl.get(cc, rr) == "L":
            self.die(game)

        if self.invuln > 0: self.invuln -= 1
        if self.star > 0: self.star -= 1

        # animation
        if abs(self.vx) > 0.2 and self.on_ground:
            self.anim += abs(self.vx) * 0.12
        else:
            self.anim = 0

        # reach flag
        if self.x + self.w >= lvl.flag_col * TILE and not self.win:
            self.win = 1
            self.x = lvl.flag_col * TILE - self.w + 2
            self.vx = 0
            game.on_flag()

    def _hit_block(self, game, cc, rr):
        ch = game.level.get(cc, rr)
        if ch == "?":
            item = game.level.qcontents.get((cc, rr), "coin")
            game.level.set(cc, rr, "Q")
            if item == "coin":
                game.add_coin(); game.popups.append(CoinPop(cc*TILE, rr*TILE))
                game.audio.play("coin")
            else:
                game.spawn_item(cc, rr, item)
                game.audio.play("power" if item != "star" else "1up")
            game.bumps.append([cc, rr, -4.0])
        elif ch == "B":
            if self.power >= 1:
                game.level.set(cc, rr, "-")
                game.audio.play("brick")
                game.shards.append(BrickShards(cc*TILE, rr*TILE, game.level.theme))
                game.add_score(50)
            else:
                game.audio.play("bump")
                game.bumps.append([cc, rr, -3.0])

    def sprite(self):
        tag = "f" if self.power == 2 else ""
        if self.power == 0:
            if not self.on_ground:
                base = SPR[f"p_small_jump{tag}"]
            elif abs(self.vx) > 0.2:
                base = SPR[f"p_small_walk{int(self.anim)%2}{tag}"]
            else:
                base = SPR[f"p_small_idle{tag}"]
        else:
            if self.crouch:
                base = SPR[f"p_big_crouch{tag}"]
            elif not self.on_ground:
                base = SPR[f"p_big_jump{tag}"]
            elif abs(self.vx) > 0.2:
                base = SPR[f"p_big_walk{int(self.anim)%3}{tag}"]
            else:
                base = SPR[f"p_big_idle{tag}"]
        if self.facing < 0:
            base = pygame.transform.flip(base, True, False)
        return base

    def draw(self, screen, cam):
        if self.invuln > 0 and (self.invuln // 3) % 2 == 0:
            return
        spr = self.sprite()
        sx = int(self.x - cam) - 2
        sy = int(self.y) - (spr.get_height() - self.h)
        if self.star > 0:
            tint = spr.copy()
            cols = [(255,80,80),(255,255,120),(120,255,120),(120,180,255)]
            tint.fill(cols[(self.star//4) % 4] + (90,), special_flags=pygame.BLEND_RGBA_ADD)
            screen.blit(tint, (sx, sy))
        else:
            screen.blit(spr, (sx, sy))


class Goomba(Entity):
    def __init__(self, x, y):
        super().__init__(x, y, 14, 14)
        self.vx = -0.5
        self.anim = 0.0
        self.squish = 0
    def update(self, game):
        if self.squish > 0:
            self.squish -= 1
            if self.squish == 0: self.alive = False
            return
        lvl = game.level
        self.vy = min(self.vy + GRAVITY, MAX_FALL)
        if tile_collide_x(self, lvl):
            self.vx = -self.vx
        for (pc, pt, ph, _) in lvl.pipes:
            pr = pygame.Rect(pc*TILE, pt*TILE, 2*TILE, ph*TILE)
            if self.rect.colliderect(pr):
                self.vx = -self.vx
                self.x += self.vx * 2
        tile_collide_y(self, lvl)
        self.anim += 0.1
        if self.y > NATIVE_H + 40: self.alive = False
    def stomp(self, game):
        self.squish = 18
        self.vx = 0
        self.h = 6; self.y += 8
        game.add_score(100)
        game.audio.play("stomp")
    def draw(self, screen, cam):
        if self.squish > 0:
            spr = SPR["goomba_flat"]
        else:
            spr = SPR[f"goomba{int(self.anim)%2}"]
        screen.blit(spr, (int(self.x - cam) - 1, int(self.y) - (16 - self.h)))


class Koopa(Entity):
    def __init__(self, x, y):
        super().__init__(x, y, 14, 14)
        self.vx = -0.5
        self.anim = 0.0
        self.shell = False
        self.shell_move = 0
        self.facing = -1
    def update(self, game):
        lvl = game.level
        self.vy = min(self.vy + GRAVITY, MAX_FALL)
        sp = self.vx
        if tile_collide_x(self, lvl):
            self.vx = -sp if sp != 0 else self.vx
        for (pc, pt, ph, _) in lvl.pipes:
            pr = pygame.Rect(pc*TILE, pt*TILE, 2*TILE, ph*TILE)
            if self.rect.colliderect(pr):
                self.vx = -self.vx; self.x += self.vx * 2
        tile_collide_y(self, lvl)
        # ledge turn (only when walking)
        if not self.shell or self.shell_move == 0:
            ahead = int((self.cx() + (8 if self.vx > 0 else -8)) // TILE)
            below = int((self.y + self.h + 2) // TILE)
            if self.on_ground and not lvl.solid(ahead, below) and self.vx != 0:
                self.vx = -self.vx
        self.anim += 0.1
        if self.shell_move:
            self._kill_enemies(game)
        if self.y > NATIVE_H + 40: self.alive = False
    def _kill_enemies(self, game):
        for e in game.enemies:
            if e is self or not e.alive: continue
            if self.rect.colliderect(e.rect):
                if isinstance(e, Goomba) and e.squish == 0:
                    e.stomp(game); e.squish = 1; e.alive = False
                    game.add_score(200)
                elif isinstance(e, Koopa) and not (e.shell and e.shell_move == 0):
                    e.alive = False; game.add_score(200)
                elif isinstance(e, Boss):
                    e.hit(game)
    def stomp(self, game):
        if not self.shell:
            self.shell = True; self.shell_move = 0; self.vx = 0
            self.h = 14
            game.audio.play("stomp")
        else:
            self.shell_move = 0; self.vx = 0
            game.audio.play("stomp")
        game.add_score(100)
    def kick(self, game, direction):
        self.shell = True
        self.shell_move = 1
        self.vx = 3.0 * direction
        game.audio.play("kick")
    def draw(self, screen, cam):
        if self.shell:
            spr = SPR["shell"]
        else:
            spr = SPR[f"koopa{int(self.anim)%2}"]
            if self.vx > 0:
                spr = pygame.transform.flip(spr, True, False)
        screen.blit(spr, (int(self.x - cam) - 1, int(self.y) - (16 - self.h)))


class Piranha(Entity):
    def __init__(self, pc, ptop):
        self.base_y = ptop * TILE
        super().__init__(pc*TILE + TILE//2 - 8, self.base_y, 16, 16)
        self.t = random.random() * 120
        self.anim = 0.0
    def update(self, game):
        self.t += 1
        phase = (self.t % 160) / 160.0
        # hide if player is right on the pipe
        px = game.player.cx()
        near = abs(px - (self.x + 8)) < 28
        if phase < 0.4 and not near:
            self.y = self.base_y - int(16 * (phase / 0.4))
        elif phase < 0.6:
            self.y = self.base_y - 16
        elif phase < 1.0 and not near:
            self.y = self.base_y - int(16 * (1 - (phase - 0.6) / 0.4))
        else:
            self.y = self.base_y
        self.anim += 0.08
    def stomp(self, game):  # not stompable
        pass
    def draw(self, screen, cam):
        if self.y < self.base_y:
            spr = SPR[f"piranha{int(self.anim)%2}"]
            screen.blit(spr, (int(self.x - cam), int(self.y)))


class Boss(Entity):
    def __init__(self, x, y):
        super().__init__(x, y, 22, 26)
        self.vx = -0.6
        self.hp = 5
        self.anim = 0.0
        self.flash = 0
    def update(self, game):
        lvl = game.level
        self.vy = min(self.vy + GRAVITY, MAX_FALL)
        if tile_collide_x(self, lvl):
            self.vx = -self.vx
        tile_collide_y(self, lvl)
        # patrol within a range
        if random.random() < 0.01:
            self.vx = -self.vx
        self.anim += 0.08
        if self.flash > 0: self.flash -= 1
    def hit(self, game):
        if self.flash > 0: return
        self.hp -= 1
        self.flash = 20
        game.audio.play("stomp")
        game.add_score(500)
        if self.hp <= 0:
            self.alive = False
            game.add_score(5000)
    def stomp(self, game):
        game.player.hurt(game)
    def draw(self, screen, cam):
        if self.flash > 0 and (self.flash // 2) % 2 == 0:
            return
        s = surf(self.w, self.h)
        rrect(s, C["koopa_dk"], (2, 8, 18, 16), 5)
        rrect(s, C["koopa"], (2, 7, 18, 14), 5)
        rrect(s, C["koopa_sk"], (5, 1, 12, 8), 4)
        pygame.draw.rect(s, C["m_red"], (6, 0, 3, 2))  # horns
        pygame.draw.rect(s, C["m_red"], (13, 0, 3, 2))
        pygame.draw.rect(s, C["black"], (8, 3, 2, 2))
        pygame.draw.rect(s, C["black"], (13, 3, 2, 2))
        pygame.draw.rect(s, C["white"], (7, 6, 8, 2))  # teeth
        screen.blit(s, (int(self.x - cam), int(self.y)))


class Fireball(Entity):
    def __init__(self, x, y, d):
        super().__init__(x, y, 8, 8)
        self.vx = 4.0 * d
        self.vy = 2.0
        self.life = 180
    def update(self, game):
        lvl = game.level
        self.vy = min(self.vy + 0.4, 6)
        if tile_collide_x(self, lvl):
            self.alive = False; return
        if tile_collide_y(self, lvl):
            self.vy = -3.5
        self.life -= 1
        if self.life <= 0 or self.y > NATIVE_H:
            self.alive = False
        for e in game.enemies:
            if e.alive and self.rect.colliderect(e.rect):
                if isinstance(e, Boss):
                    e.hit(game); self.alive = False
                elif isinstance(e, Piranha):
                    pass
                else:
                    e.alive = False; game.add_score(100); self.alive = False
    def draw(self, screen, cam):
        screen.blit(SPR["fireball"], (int(self.x - cam), int(self.y)))


class Item(Entity):
    def __init__(self, x, y, kind):
        super().__init__(x, y, 14, 14)
        self.kind = kind
        self.emerge = 16        # rises out of block
        self.anim = 0.0
        if kind in ("mush", "star", "1up"):
            self.vx = 1.0
    def update(self, game):
        lvl = game.level
        if self.emerge > 0:
            self.y -= 1; self.emerge -= 1
            return
        if self.kind == "flower":
            self.anim += 0.15
            return
        self.vy = min(self.vy + GRAVITY, MAX_FALL)
        if self.kind == "star":
            if self.on_ground: self.vy = -5
        if tile_collide_x(self, lvl):
            self.vx = -self.vx
        for (pc, pt, ph, _) in lvl.pipes:
            pr = pygame.Rect(pc*TILE, pt*TILE, 2*TILE, ph*TILE)
            if self.rect.colliderect(pr):
                self.vx = -self.vx; self.x += self.vx
        tile_collide_y(self, lvl)
        self.anim += 0.1
        if self.y > NATIVE_H + 20: self.alive = False
    def collect(self, game):
        self.alive = False
        p = game.player
        if self.kind == "mush":
            if p.power == 0: p.set_power(1)
            game.add_score(1000); game.audio.play("power")
        elif self.kind == "flower":
            p.set_power(2 if p.power >= 1 else 1)
            game.add_score(1000); game.audio.play("power")
        elif self.kind == "star":
            p.star = 600; game.add_score(1000); game.audio.play("1up")
        elif self.kind == "1up":
            game.lives += 1; game.audio.play("1up")
    def draw(self, screen, cam):
        if self.kind == "mush": spr = SPR["mushroom"]
        elif self.kind == "1up": spr = SPR["oneup"]
        elif self.kind == "flower": spr = SPR[f"flower{int(self.anim)%4}"]
        else: spr = SPR[f"star{int(self.anim)%2}"]
        screen.blit(spr, (int(self.x - cam), int(self.y)))


class CoinPop:
    def __init__(self, x, y):
        self.x = x; self.y = y; self.vy = -4.5; self.life = 24
    def update(self):
        self.y += self.vy; self.vy += 0.35; self.life -= 1
    def draw(self, screen, cam):
        f = (24 - self.life) // 3
        screen.blit(SPR[f"coin{f%4}"], (int(self.x - cam), int(self.y)))

class BrickShards:
    def __init__(self, x, y, theme):
        col = C["brick"]
        if theme == "under": col = C["u_brick"]
        if theme == "castle": col = C["c_brick"]
        self.col = col
        self.parts = []
        for dx, dy in ((0,0),(8,0),(0,8),(8,8)):
            self.parts.append([x+dx, y+dy, (dx-4)*0.4, -4 + dy*0.2])
        self.life = 40
    def update(self):
        for p in self.parts:
            p[0] += p[2]; p[1] += p[3]; p[3] += 0.4
        self.life -= 1
    def draw(self, screen, cam):
        for p in self.parts:
            pygame.draw.rect(screen, self.col, (int(p[0]-cam), int(p[1]), 6, 6))


# ----------------------------------------------------------------------------
#  BACKGROUND DECOR (procedural clouds / hills / bushes)
# ----------------------------------------------------------------------------
def draw_cloud(screen, x, y):
    for dx, dy, r in ((0,4,5),(7,2,6),(15,3,5),(22,5,4)):
        pygame.draw.circle(screen, C["cloud_sh"], (x+dx, y+dy+1), r)
    for dx, dy, r in ((0,3,5),(7,1,6),(15,2,5),(22,4,4)):
        pygame.draw.circle(screen, C["cloud"], (x+dx, y+dy), r)

def draw_hill(screen, x, y, big):
    w = 48 if big else 30
    pygame.draw.ellipse(screen, C["hill_dk"], (x, y, w, w//2 + 6))
    pygame.draw.ellipse(screen, C["hill"], (x+2, y, w-4, w//2))

def draw_bush(screen, x, y):
    for dx, r in ((0,6),(8,8),(17,6)):
        pygame.draw.circle(screen, C["hill_dk"], (x+dx, y+1), r)
    for dx, r in ((0,6),(8,8),(17,6)):
        pygame.draw.circle(screen, C["bush"], (x+dx, y), r)


# ----------------------------------------------------------------------------
#  GAME
# ----------------------------------------------------------------------------
class Game:
    STATE_TITLE = 0
    STATE_PLAY = 1
    STATE_CLEAR = 2
    STATE_DEAD = 3
    STATE_OVER = 4
    STATE_WIN = 5

    def __init__(self):
        pygame.init()
        try:
            self.font = pygame.font.Font(None, 16)
            self.bigfont = pygame.font.Font(None, 28)
        except Exception:
            self.font = pygame.font.SysFont("monospace", 12)
            self.bigfont = pygame.font.SysFont("monospace", 24)
        self.screen = pygame.display.set_mode((WIN_W, WIN_H))
        pygame.display.set_caption("SMB Famicom Edition - Team Flames / Samsoft")
        self.native = surf(NATIVE_W, NATIVE_H)
        self.clock = pygame.time.Clock()
        self.audio = Audio()
        build_player_sprites()
        build_enemy_sprites()
        build_item_sprites()
        self.world = 1
        self.stage = 1
        self.score = 0
        self.coins = 0
        self.lives = 3
        self.state = self.STATE_TITLE
        self.timer_frames = 0
        self.msg_timer = 0
        self.decor = []
        self.running = True

    # --- level lifecycle ---
    def load_level(self):
        self.level = Level(self.world, self.stage)
        self.player = Player(self.level.start_col * TILE, (ROWS - 3) * TILE)
        self.enemies = []
        self.items = []
        self.fireballs = []
        self.popups = []
        self.shards = []
        self.bumps = []        # [col,row,vy]
        for (col, row, kind) in self.level.enemies:
            ex, ey = col * TILE, row * TILE
            if kind == "goomba": self.enemies.append(Goomba(ex, ey))
            elif kind == "koopa": self.enemies.append(Koopa(ex, ey))
            elif kind == "boss": self.enemies.append(Boss(ex, ey - 12))
        for (pc, ptop, ph, pir) in self.level.pipes:
            if pir:
                self.enemies.append(Piranha(pc, ptop))
        self.cam_x = 0
        self.time = 400
        self.timer_frames = 0
        self._build_decor()
        self._theme_key = self.level.theme        # 'over'|'under'|'sky'|'castle'
        self.state = self.STATE_PLAY
        self.msg_timer = 90
        self.audio.play_music(self._theme_key, self.world)

    def _build_decor(self):
        self.decor = []
        rng = random.Random(self.world * 7 + self.stage)
        if self.level.theme in ("over", "sky"):
            for _ in range(self.level.width // 18):
                x = rng.randint(0, self.level.width * TILE)
                self.decor.append(("cloud", x, rng.randint(12, 70)))
            for _ in range(self.level.width // 22):
                x = rng.randint(0, self.level.width * TILE)
                self.decor.append(("hill", x, (ROWS-2)*TILE - 18, rng.random() < 0.5))
            for _ in range(self.level.width // 16):
                x = rng.randint(0, self.level.width * TILE)
                self.decor.append(("bush", x, (ROWS-2)*TILE - 6))

    def add_score(self, n): self.score += n
    def add_coin(self):
        self.coins += 1
        self.score += 200
        if self.coins >= 100:
            self.coins -= 100; self.lives += 1; self.audio.play("1up")
    def spawn_item(self, cc, rr, kind):
        self.items.append(Item(cc*TILE + 1, rr*TILE, kind))

    def on_flag(self):
        self.audio.play("flag")
        self.audio.play_jingle("clear")
        self.state = self.STATE_CLEAR
        self.clear_timer = 150
        self.add_score(2000)

    def next_level(self):
        self.stage += 1
        if self.stage > 8:
            self.stage = 1
            self.world += 1
        if self.world > 8:
            self.state = self.STATE_WIN
            self.audio.stop_music()
        else:
            self.load_level()

    def player_died(self):
        self.lives -= 1
        if self.lives <= 0:
            self.state = self.STATE_OVER
            self.over_timer = 180
        else:
            self.load_level()

    # --- main loop ---
    def run(self, max_frames=None):
        frames = 0
        while self.running:
            keys = pygame.key.get_pressed()
            for e in pygame.event.get():
                if e.type == pygame.QUIT:
                    self.running = False
                elif e.type == pygame.KEYDOWN:
                    if e.key == pygame.K_ESCAPE:
                        self.running = False
                    if e.key == pygame.K_RETURN:
                        if self.state == self.STATE_TITLE:
                            self.world = 1; self.stage = 1
                            self.score = 0; self.coins = 0; self.lives = 3
                            self.load_level()
                        elif self.state in (self.STATE_OVER, self.STATE_WIN):
                            self.state = self.STATE_TITLE

            self.update(keys)
            self.draw()
            pygame.display.flip()
            self.clock.tick(FPS)
            frames += 1
            if max_frames is not None and frames >= max_frames:
                break
        pygame.quit()

    def update(self, keys):
        if self.state == self.STATE_TITLE:
            if self.audio.cur is not None:     # OST only plays inside levels
                self.audio.stop_music()
        if self.state == self.STATE_PLAY:
            self._update_play(keys)
        elif self.state == self.STATE_CLEAR:
            self.player.x += 0.6
            self.clear_timer -= 1
            if self.time > 0:
                self.time -= 1; self.score += 10
            if self.clear_timer <= 0:
                self.next_level()
        elif self.state == self.STATE_DEAD:
            self.player.update(self, keys)
            self.dead_timer -= 1
            if self.dead_timer <= 0:
                self.player_died()
        elif self.state == self.STATE_OVER:
            self.over_timer -= 1
            if self.over_timer <= 0:
                self.state = self.STATE_TITLE

    def _update_play(self, keys):
        p = self.player
        p.update(self, keys)
        if p.dead:
            self.state = self.STATE_DEAD
            self.dead_timer = 120
            return
        if p.win:                      # reached flag this frame -> let jingle play
            return

        # soundtrack: star-power rush vs the stage theme
        self.audio.play_music("star" if p.star > 0 else self._theme_key, self.world)

        # camera follows, never scrolls back
        target = p.x - NATIVE_W * 0.42
        if target > self.cam_x:
            self.cam_x = target
        self.cam_x = max(0, min(self.cam_x, self.level.width * TILE - NATIVE_W))

        view = pygame.Rect(self.cam_x - 32, 0, NATIVE_W + 80, NATIVE_H)
        for e in self.enemies:
            if not e.alive: continue
            if isinstance(e, (Piranha,)) or view.colliderect(e.rect) or e.x < self.cam_x + NATIVE_W + 60:
                e.update(self)
            self._player_enemy(p, e)
        self.enemies = [e for e in self.enemies if e.alive]

        for it in self.items:
            if it.alive:
                it.update(self)
                if it.rect.colliderect(p.rect):
                    it.collect(self)
        self.items = [i for i in self.items if i.alive]

        for f in self.fireballs:
            if f.alive: f.update(self)
        self.fireballs = [f for f in self.fireballs if f.alive]

        for cp in self.popups: cp.update()
        self.popups = [c for c in self.popups if c.life > 0]
        for sh in self.shards: sh.update()
        self.shards = [s for s in self.shards if s.life > 0]
        for b in self.bumps:
            b[2] += 0.7          # bumped block springs up then settles
        self.bumps = [b for b in self.bumps if b[2] <= 0]

        # timer
        self.timer_frames += 1
        if self.timer_frames >= 24:
            self.timer_frames = 0
            self.time -= 1
            if self.time <= 0:
                p.die(self)
        if self.msg_timer > 0: self.msg_timer -= 1

    def _player_enemy(self, p, e):
        if p.dead or p.win or not e.alive: return
        if not p.rect.colliderect(e.rect): return
        # star power kills
        if p.star > 0 and not isinstance(e, Boss):
            e.alive = False; self.add_score(200); self.audio.play("kick"); return
        # stomp check
        falling = p.vy > 0 and (p.y + p.h) - e.y < 12
        if isinstance(e, Koopa):
            if e.shell and e.shell_move == 0:
                # kick stationary shell
                d = 1 if p.cx() < e.cx() else -1
                e.kick(self, d); p.vy = -3
                return
            if falling:
                e.stomp(self); p.vy = P_STOMP_BOUNCE
            elif e.shell and e.shell_move != 0:
                p.hurt(self)
            else:
                p.hurt(self)
        elif isinstance(e, Goomba):
            if falling and e.squish == 0:
                e.stomp(self); p.vy = P_STOMP_BOUNCE
            elif e.squish == 0:
                p.hurt(self)
        elif isinstance(e, Boss):
            p.hurt(self)
        elif isinstance(e, Piranha):
            if e.y < e.base_y:
                p.hurt(self)

    # --- rendering ---
    def draw(self):
        s = self.native
        if self.state == self.STATE_TITLE:
            self._draw_title(s)
        elif self.state in (self.STATE_PLAY, self.STATE_CLEAR, self.STATE_DEAD):
            self._draw_world(s)
        elif self.state == self.STATE_OVER:
            s.fill(C["black"])
            self._center(s, "GAME OVER", self.bigfont, C["white"], NATIVE_H//2 - 10)
        elif self.state == self.STATE_WIN:
            s.fill(C["sky"])
            self._center(s, "THANK YOU!", self.bigfont, C["white"], 80)
            self._center(s, "YOU SAVED THE KINGDOM", self.font, C["white"], 120)
            self._center(s, f"SCORE {self.score}", self.font, C["star"], 140)
            self._center(s, "PRESS ENTER", self.font, C["white"], 170)
        scaled = pygame.transform.scale(s, (WIN_W, WIN_H))
        self.screen.blit(scaled, (0, 0))

    def _center(self, s, text, font, color, y):
        t = font.render(text, False, color)
        s.blit(t, (NATIVE_W//2 - t.get_width()//2, y))

    def _draw_title(self, s):
        s.fill(C["sky"])
        for i, (x, y) in enumerate(((30, 30), (180, 50), (90, 24))):
            draw_cloud(s, x, y)
        draw_hill(s, 20, NATIVE_H-50, True)
        draw_hill(s, 180, NATIVE_H-44, False)
        for x in range(0, NATIVE_W, TILE):
            s.blit(make_tile("ground", "over"), (x, NATIVE_H-TILE))
            s.blit(make_tile("ground", "over"), (x, NATIVE_H-2*TILE))
        self._center(s, "SUPER  MARIO  BROS", self.bigfont, C["m_red"], 56)
        self._center(s, "FAMICOM  EDITION", self.font, C["white"], 84)
        # hero on the ground
        s.blit(SPR["p_big_idle"], (NATIVE_W//2 - 8, NATIVE_H - 2*TILE - 28))
        s.blit(SPR["goomba0"], (NATIVE_W//2 + 30, NATIVE_H - 2*TILE - 16))
        if (pygame.time.get_ticks() // 400) % 2 == 0:
            self._center(s, "PRESS  ENTER", self.font, C["black"], 150)
        self._center(s, "Team Flames / Samsoft  (c)1999-2026", self.font, C["sky_dk"], NATIVE_H-2*TILE-12)

    def _draw_world(self, s):
        lvl = self.level
        cam = int(self.cam_x)
        s.fill(lvl.bg)
        # decor
        for d in self.decor:
            if d[0] == "cloud":
                _, x, y = d
                if -40 < x - cam < NATIVE_W: draw_cloud(s, x - cam, y)
            elif d[0] == "hill":
                _, x, y, big = d
                if -60 < x - cam < NATIVE_W: draw_hill(s, x - cam, y, big)
            elif d[0] == "bush":
                _, x, y = d
                if -40 < x - cam < NATIVE_W: draw_bush(s, x - cam, y)

        # tiles
        c0 = cam // TILE
        c1 = c0 + COLS_VIS + 2
        bumpmap = {(b[0], b[1]): b[2] for b in self.bumps}
        for col in range(c0, c1):
            for row in range(ROWS):
                ch = lvl.get(col, row)
                if ch == "-" or ch == "|" or ch == "X":
                    continue
                dy = 0
                if (col, row) in bumpmap:
                    dy = int(bumpmap[(col, row)])
                if ch == "#": img = make_tile("ground", lvl.theme)
                elif ch == "B": img = make_tile("brick", lvl.theme)
                elif ch == "?": img = make_tile("qblock", lvl.theme)
                elif ch == "Q": img = make_tile("used", lvl.theme)
                elif ch == "S": img = make_tile("stair", lvl.theme)
                elif ch == "L": img = make_tile("lava", lvl.theme)
                else: continue
                s.blit(img, (col*TILE - cam, row*TILE + dy))

        # pipes
        for (pc, ptop, ph, _) in lvl.pipes:
            self._draw_pipe(s, pc, ptop, ph, cam)

        # flagpole / axe
        fc = lvl.flag_col
        if c0 <= fc <= c1:
            px = fc*TILE - cam + 6
            pygame.draw.rect(s, C["pole_dk"], (px, TILE, 4, (ROWS-3)*TILE))
            pygame.draw.rect(s, C["pole"], (px, TILE, 2, (ROWS-3)*TILE))
            pygame.draw.circle(s, C["star"], (px+2, TILE), 4)
            if not lvl.is_castle:
                pygame.draw.polygon(s, C["flag"], [(px-2, TILE+6), (px-2, TILE+18), (px-14, TILE+12)])
            else:
                pygame.draw.rect(s, C["star"], (px-8, TILE-2, 8, 6))  # axe

        # entities
        for it in self.items: it.draw(s, cam)
        for sh in self.shards: sh.draw(s, cam)
        for cp in self.popups: cp.draw(s, cam)
        for e in self.enemies:
            if e.x - cam < NATIVE_W + 20 and e.x - cam > -30:
                e.draw(s, cam)
        for f in self.fireballs: f.draw(s, cam)
        self.player.draw(s, cam)

        self._draw_hud(s)
        if self.msg_timer > 0:
            self._center(s, f"WORLD {self.world}-{self.stage}", self.bigfont, C["white"], NATIVE_H//2 - 12)
        if self.state == self.STATE_CLEAR:
            self._center(s, "COURSE CLEAR!", self.bigfont, C["star"], 40)

    def _draw_pipe(self, s, pc, ptop, ph, cam):
        x = pc*TILE - cam
        w = 2*TILE
        # body
        for r in range(ph):
            yy = (ptop + r) * TILE
            pygame.draw.rect(s, C["pipe_dk"], (x, yy, w, TILE))
            pygame.draw.rect(s, C["pipe"], (x+2, yy, w-6, TILE))
            pygame.draw.rect(s, C["pipe_lt"], (x+3, yy, 3, TILE))
        # rim
        yy = ptop * TILE
        pygame.draw.rect(s, C["pipe_dk"], (x-2, yy, w+4, 6))
        pygame.draw.rect(s, C["pipe"], (x, yy, w, 4))
        pygame.draw.rect(s, C["pipe_lt"], (x+1, yy, 4, 4))

    def _draw_hud(self, s):
        def txt(t, x, y, col=C["white"]):
            s.blit(self.font.render(t, False, col), (x, y))
        txt("MARIO", 12, 6)
        txt(f"{self.score:06d}", 12, 16)
        txt("x{:02d}".format(self.coins), 92, 16, C["star"])
        pygame.draw.circle(s, C["coin"], (88, 19), 3)
        txt("WORLD", 150, 6)
        txt(f"{self.world}-{self.stage}", 158, 16)
        txt("TIME", 210, 6)
        txt(f"{max(0,self.time):03d}", 214, 16)
        txt(f"LIVES {self.lives}", 12, 28, C["m_red"])


# ----------------------------------------------------------------------------
#  ENTRY
# ----------------------------------------------------------------------------
def main():
    import os
    headless = os.environ.get("SCB_HEADLESS") == "1"
    game = Game()
    if headless:
        # smoke test: run a scripted slice of every level, no window needed
        game.run(max_frames=3)
    else:
        game.run()

if __name__ == "__main__":
    main()
